### ISSUE TITLE
Binary tarball link is broken

### ISSUE THREAD

**Issue by krother** [pjotrp/guix-notes#9]
I tried to follow the installation instructions and got stuck in the section https://github.com/pjotrp/guix-notes/blob/master/INSTALL.org#binary-installation 

I cannot find a link to the tarball, and the links in the article on http://elephly.net/posts/2015-06-21-getting-started-with-guix.html are broken.

**Comment by Brainiarc7** [comment]
Hey,

You can always substitute the link to that of the latest Guix binary, which is on:

https://www.gnu.org/software/guix/download/

Here, you can then pick the binary of choice depending on your platform (mips, x86, x64 or armhf). (The binary package may get updated and the notes will not always reflect that).

**Comment by krother** [comment]
Thanks for quick response. The link on the page is 404ing: ftp://alpha.gnu.org/gnu/guix/guix-binary-0.10.0.x86_64-linux.tar.xz . Could be temporary. I'll check later today.

**Comment by Brainiarc7** [comment]
Hey,

The link is working (And you can fetch the tarball with wget).

Are you behind a proxy or a corporate network connection?

**Comment by pjotrp** [comment]
@krother probably proxy issue. The link on guix-notes is out of data, it will always be ;). I'll remove the URL.

**Comment by krother** [comment]
Without a proxy, the download works fine. closing.

**Comment by pjotrp** [comment]
Fixed documentation with https://github.com/pjotrp/guix-notes/commit/55dc92a4de2ba437a679637e824fc8a24cb64892
